### ISSUE TITLE
Should Original Image be fed to OOT pipeline during inference?

### ISSUE THREAD

**Issue by Ezhil6999** [levihsu/OOTDiffusion#144]
I was looking through the code and was not able to understand why original image is being fed to the pipeline during inference. I noticed that noise is being added to the original image in the latent space but I believe noise must be added to the masked image alone.
Check out these lines
https://github.com/levihsu/OOTDiffusion/blob/main/ootd/pipelines_ootd/pipeline_ootd.py#L410
https://github.com/levihsu/OOTDiffusion/blob/main/ootd/pipelines_ootd/pipeline_ootd.py#L415

can you please clarify if my understanding is correct?

**Comment by levihsu** [comment]
In inference, the noise is concatenated with the masked image rather than adding
https://github.com/levihsu/OOTDiffusion/blob/218c4c63396e89ed86374b44c04a3dfe81dcaf82/ootd/pipelines_ootd/pipeline_ootd.py#L367

Here the original image is used to mitigate the reconstruction error of the unmasked region (aka an optional postprocessing)
