### ISSUE TITLE
ValueError: Cannot load ../checkpoints/ootd/ootd_hd/checkpoint-36000

### ISSUE THREAD

**Issue by SilentTE** [levihsu/OOTDiffusion#34]
File "/root/OOTDiffusion/run/run_ootd.py", line 47, in <module>
    model = OOTDiffusionHD(args.gpu_id)
  File "/root/OOTDiffusion/ootd/inference_ootd_hd.py", line 57, in __init__
    unet_vton = UNetVton2DConditionModel.from_pretrained(
  File "/root/anaconda3/envs/ootd/lib/python3.10/site-packages/diffusers/models/modeling_utils.py", line 812, in from_pretrained
    unexpected_keys = load_model_dict_into_meta(
  File "/root/anaconda3/envs/ootd/lib/python3.10/site-packages/diffusers/models/modeling_utils.py", line 155, in load_model_dict_into_meta
    raise ValueError(
ValueError: Cannot load ../checkpoints/ootd/ootd_hd/checkpoint-36000 because conv_in.weight expected shape tensor(..., device='meta', size=(320, 8, 3, 3)), but got torch.Size([320, 4, 3, 3]). If you want to instead overwrite randomly initialized weights, please make sure to pass both `low_cpu_mem_usage=False` and `ignore_mismatched_sizes=True`.

**Comment by SilentTE** [comment]
how to solve it?

**Comment by CFengFeng** [comment]
The config attributes {'architectures': ['CLIPModel'], 'initializer_factor': 1.0, 'logit_scale_init_value': 2.6592, 'model_type': 'clip', 'projection_dim': 768, 'text_config': {'_name_or_path': '', 'add_cross_attention': False, 'architectures': None, 'attention_dropout': 0.0, 'bad_words_ids': None, 'bos_token_id': 0, 'chunk_size_feed_forward': 0, 'cross_attention_hidden_size': None, 'decoder_start_token_id': None, 'diversity_penalty': 0.0, 'do_sample': False, 'dropout': 0.0, 'early_stopping': False, 'encoder_no_repeat_ngram_size': 0, 'eos_token_id': 2, 'finetuning_task': None, 'forced_bos_token_id': None, 'forced_eos_token_id': None, 'hidden_act': 'quick_gelu', 'hidden_size': 768, 'id2label': {'0': 'LABEL_0', '1': 'LABEL_1'}, 'initializer_factor': 1.0, 'initializer_range': 0.02, 'intermediate_size': 3072, 'is_decoder': False, 'is_encoder_decoder': False, 'label2id': {'LABEL_0': 0, 'LABEL_1': 1}, 'layer_norm_eps': 1e-05, 'length_penalty': 1.0, 'max_length': 20, 'max_position_embeddings': 77, 'min_length': 0, 'model_type': 'clip_text_model', 'no_repeat_ngram_size': 0, 'num_attention_heads': 12, 'num_beam_groups': 1, 'num_beams': 1, 'num_hidden_layers': 12, 'num_return_sequences': 1, 'output_attentions': False, 'output_hidden_states': False, 'output_scores': False, 'pad_token_id': 1, 'prefix': None, 'problem_type': None, 'projection_dim': 768, 'pruned_heads': {}, 'remove_invalid_values': False, 'repetition_penalty': 1.0, 'return_dict': True, 'return_dict_in_generate': False, 'sep_token_id': None, 'task_specific_params': None, 'temperature': 1.0, 'tie_encoder_decoder': False, 'tie_word_embeddings': True, 'tokenizer_class': None, 'top_k': 50, 'top_p': 1.0, 'torch_dtype': None, 'torchscript': False, 'transformers_version': '4.16.0.dev0', 'use_bfloat16': False, 'vocab_size': 49408}, 'text_config_dict': {'hidden_size': 768, 'intermediate_size': 3072, 'num_attention_heads': 12, 'num_hidden_layers': 12, 'projection_dim': 768}, 'torch_dtype': 'float32', 'transformers_version': None, 'vision_config': {'_name_or_path': '', 'add_cross_attention': False, 'architectures': None, 'attention_dropout': 0.0, 'bad_words_ids': None, 'bos_token_id': None, 'chunk_size_feed_forward': 0, 'cross_attention_hidden_size': None, 'decoder_start_token_id': None, 'diversity_penalty': 0.0, 'do_sample': False, 'dropout': 0.0, 'early_stopping': False, 'encoder_no_repeat_ngram_size': 0, 'eos_token_id': None, 'finetuning_task': None, 'forced_bos_token_id': None, 'forced_eos_token_id': None, 'hidden_act': 'quick_gelu', 'hidden_size': 1024, 'id2label': {'0': 'LABEL_0', '1': 'LABEL_1'}, 'image_size': 224, 'initializer_factor': 1.0, 'initializer_range': 0.02, 'intermediate_size': 4096, 'is_decoder': False, 'is_encoder_decoder': False, 'label2id': {'LABEL_0': 0, 'LABEL_1': 1}, 'layer_norm_eps': 1e-05, 'length_penalty': 1.0, 'max_length': 20, 'min_length': 0, 'model_type': 'clip_vision_model', 'no_repeat_ngram_size': 0, 'num_attention_heads': 16, 'num_beam_groups': 1, 'num_beams': 1, 'num_hidden_layers': 24, 'num_return_sequences': 1, 'output_attentions': False, 'output_hidden_states': False, 'output_scores': False, 'pad_token_id': None, 'patch_size': 14, 'prefix': None, 'problem_type': None, 'projection_dim': 768, 'pruned_heads': {}, 'remove_invalid_values': False, 'repetition_penalty': 1.0, 'return_dict': True, 'return_dict_in_generate': False, 'sep_token_id': None, 'task_specific_params': None, 'temperature': 1.0, 'tie_encoder_decoder': False, 'tie_word_embeddings': True, 'tokenizer_class': None, 'top_k': 50, 'top_p': 1.0, 'torch_dtype': None, 'torchscript': False, 'transformers_version': '4.16.0.dev0', 'use_bfloat16': False}, 'vision_config_dict': {'hidden_size': 1024, 'intermediate_size': 4096, 'num_attention_heads': 16, 'num_hidden_layers': 24, 'patch_size': 14, 'projection_dim': 768}} were passed to AutoencoderKL, but are not expected and will be ignored. Please verify your config.json configuration file.
Traceback (most recent call last):
  File "/home/app/workspace/OOTDiffusion/run/graido_ootd.py", line 28, in <module>
    ootd_model_hd = OOTDiffusionHD(0)
  File "/home/app/workspace/OOTDiffusion/ootd/inference_ootd_hd.py", line 45, in __init__
    vae = AutoencoderKL.from_pretrained(
  File "/home/app/miniconda3/envs/ootd/lib/python3.10/site-packages/diffusers/models/modeling_utils.py", line 812, in from_pretrained
    unexpected_keys = load_model_dict_into_meta(
  File "/home/app/miniconda3/envs/ootd/lib/python3.10/site-packages/diffusers/models/modeling_utils.py", line 155, in load_model_dict_into_meta
    raise ValueError(
ValueError: Cannot load ../checkpoints/ootd because encoder.conv_in.weight expected shape tensor(..., device='meta', size=(64, 3, 3, 3)), but got torch.Size([128, 3, 3, 3]). If you want to instead overwrite randomly initialized weights, please make sure to pass both `low_cpu_mem_usage=False` and `ignore_mismatched_sizes=True`. For more information, see also: https://github.com/huggingface/diffusers/issues/1619#issuecomment-1345604389 as an example.

**Comment by CFengFeng** [comment]
: 16, 'num_hidden_layers': 24, 'patch_size': 14, 'projection_dim': 768}} were passed to AutoencoderKL, but are not expected and will be ignored. Please verify your config.json configuration file.
Traceback (most recent call last):
  File "/home/app/workspace/OOTDiffusion/run/graido_ootd.py", line 28, in <module>
    ootd_model_hd = OOTDiffusionHD(0)
  File "/home/app/workspace/OOTDiffusion/ootd/inference_ootd_hd.py", line 45, in __init__
    vae = AutoencoderKL.from_pretrained(
  File "/home/app/miniconda3/envs/ootd/lib/python3.10/site-packages/diffusers/models/modeling_utils.py", line 812, in from_pretrained
    unexpected_keys = load_model_dict_into_meta(
  File "/home/app/miniconda3/envs/ootd/lib/python3.10/site-packages/diffusers/models/modeling_utils.py", line 155, in load_model_dict_into_meta
    raise ValueError(
ValueError: Cannot load ../checkpoints/ootd because encoder.conv_in.weight expected shape tensor(..., device='meta', size=(64, 3, 3, 3)), but got torch.Size([128, 3, 3, 3]). If you want to instead overwrite randomly initialized weights, please make sure to pass both `low_cpu_mem_usage=False` and `ignore_mismatched_sizes=True`. For more information, see also: https://github.com/huggingface/diffusers/issues/1619#issuecomment-1345604389 as an example.

**Comment by CFengFeng** [comment]
same problem

**Comment by julian-useraspberry** [comment]
+1, please add the weights to the Hugging Face repo

**Comment by chfeng-cs** [comment]
I encounterd the same problem as you.

**Comment by levihsu** [comment]
https://github.com/levihsu/OOTDiffusion/issues/82#issuecomment-1975955294

**Comment by ShashwatNigam99** [comment]
@CFengFeng I am facing the same problem as you

ValueError: Cannot load ../checkpoints/ootd because encoder.conv_in.weight expected shape tensor(..., device='meta', size=(64, 3, 3, 3)), but got torch.Size([128, 3, 3, 3]). If you want to instead overwrite randomly initialized weights, please make sure to pass both `low_cpu_mem_usage=False` and `ignore_mismatched_sizes=True`. For more information, see also: https://github.com/huggingface/diffusers/issues/1619#issuecomment-1345604389 as an example.

when trying to run run_ootd with either of dc or hd models

I got the weights from https://huggingface.co/levihsu/OOTDiffusion/tree/main/checkpoints/ootd
