### ISSUE TITLE
It seems not well

### ISSUE THREAD

**Issue by sswink** [levihsu/OOTDiffusion#56]
Thanks for the project, but it didn't work very well when I tried it
This is OOT:
![oot](https://github.com/levihsu/OOTDiffusion/assets/30194825/7f0c22cb-77d5-43e6-bda6-22b3f8c70485)
This is Outfit Anyone:
![outfit](https://github.com/levihsu/OOTDiffusion/assets/30194825/c91d7f8c-a9ea-4cbd-bae5-eadf17e27fe2)

**Comment by levihsu** [comment]
Hi. We recommend using ***3:4*** garment image with ***white background*** as input. Even for your current result, our detail preservation looks better (see the little flower). By the way, our OOTDiffusion supports various models rather than several fixed examples. We will continue imporving our method : )
